// Catalogo onde esta a lista dos produtos exibidos.



export const catalogo = [
    {
      id: 1,
      nome: "Pista de Carrinho de Brinquedo Polícia Bombeiro Kit Rampa 2",
      loja: "TicTac",
      preco: 98.9,
      imagem: "product-1.jpg",
      feminino: false,
      video: "",
    },
    {
      id: 2,
      nome: "Bang Toys - Veículo Elétrico Mercedez Bens, Branco",
      loja: "TicTac",
      preco: 1.649,
      imagem: "product-2.jpg",
      feminino: false,
      video: "video2.mp4",
    },
    {
      id: 3,
      nome: "Boneco Marvel Olympus Homem Aranha",
      loja: "TicTac",
      preco: 66.49,
      imagem: "product-3.jpg",
      feminino: false,
      video: "video3.mp4",
    },
    {
      id: 4,
      nome: "Brinquedo Educativo Kit Cozinha Com Frutas 23 Peças",
      loja: "TicTac",
      preco: 197.0,
      imagem: "product-4.jpg",
      feminino: true,
      video: "",
    },
    {
      id: 5,
      nome: "Boneca Brinquedo Menina Baby Conjunto Carrinho Banheirinha",
      loja: "TicTac",
      preco: 47.33,
      imagem: "product-5.jpeg",
      feminino: true,
      video: "video5.mp4",
    },
    {
      id: 6,
      nome: "Carrinho Fofomóvel Relâmpago McQueen Lider Brinquedos",
      loja: "TicTac",
      preco: 67.2,
      imagem: "product-6.png",
      feminino: false,
      video: "video6.mp4",
    },
    {
      id: 7,
      nome: "Casinha de Brinquedo E Boneca Unicórnio Freso",
      loja: "TicTac",
      preco: 3.659,
      imagem: "product-7.jpeg",
      feminino: true,
      video: "video7.mp4",
    },
    {
      id: 8,
      nome: "4 estilo crianças brinquedos de cozinha",
      loja: "TicTac",
      preco: 81.3,
      imagem: "product-8.jpeg",
      feminino: true,
      video: "",
    },
    {
      id: 9,
      nome: "Parque Diversão Da Judy Roda Gigante Brinquedo Samba Toys",
      loja: "TicTac",
      preco: 72.9,
      imagem: "product-9.jpeg",
      feminino: true,
      video: "",
    },
    {
      id: 10,
      nome: "Bebe Conforto Brinquedo Infantil Feminino Com Acessórios Papinha",
      loja: "TicTac",
      preco: 79.9,
      imagem: "product-10.jpeg",
      feminino: true,
      video: "",
    },
    {
      id: 11,
      nome: "Brinquedo Candide Carro De Controle Remoto Charge - 7 Funções",
      loja: "TicTac",
      preco: 109.9,
      imagem: "product-11.jpeg",
      feminino: false,
      video: "video11.mp4",
    },
    {
      id: 12,
      nome: "Kit C/ 3 Brinquedos - Airfray, Cafeteira, Batedeira ",
      loja: "TicTac",
      preco: 559.9,
      imagem: "product-12.jpeg",
      feminino: true,
      video: "video12.mp4",
    },
    {
      id: 13,
      nome: "KEIUMI Criança Reborn Boneca 49 CM Real Touch Full Silicone",
      loja: "TicTac",
      preco: 298.0,
      imagem: "product-13.jpeg",
      feminino: true,
      video: "video13.mp4",
    },
    {
      id: 14,
      nome: "Boneca De Vinil Influencer Digital Baby Brinquedos Menina",
      loja: "TicTac",
      preco: 75.98,
      imagem: "product-14.jpeg",
      feminino: true,
      video: "",
    },
    {
      id: 15,
      nome: "Playground Play Kids",
      loja: "TicTac",
      preco: 1.045,
      imagem: "product-15.jpeg",
      feminino: false,
      video: "",
    },
    {
      id: 16,
      nome: "Maral Spider - Quadriciclo",
      loja: "TicTac",
      preco: 412.5,
      imagem: "product-16.jpg",
      feminino: false,
      video: "video16.mp4",
    },
  ];